FOSSEE/eSim

- src/kicadtoNgspice/Analysis.py
Description : Some changes in code in AC and Transient Grid.
> Subject :Analysis Insister

- src/kicadtoNgspice/Analysis.py
Description: Modification in code in DC grid
> Subject: Analysis inserter

- install-linux.sh
install-linux.sh will now download nghdl from git and install it.
> integrating nghdl with eSim

- install-linux.sh
> Revert "integrating nghdl with eSim"

- CONTRIBUTION.md
- README.md
Improved README.md file added CONTRIBUTION.md file.
Resolves #79
> Issue number 79 solved.

- src/browser/UserManual.py
- src/browser/Welcome.py
- src/configuration/Appconfig.py
- src/frontEnd/Application.py
- src/frontEnd/DockArea.py
- src/frontEnd/ProjectExplorer.py
- src/frontEnd/Workspace.py
- src/subcircuit/Subcircuit.py
- src/subcircuit/convertSub.py
- src/subcircuit/newSub.py
- src/subcircuit/openSub.py
Changed documentation of files according to Sphinx format (reST).
> Documentation

- src/modelEditor/ModelEditor.py
**PR Details-**
**Resolves** #91
- Changed format of `.lib` files from multiple line format to single line format
> Resolves #91

- conf.py
- setup.py
- src/frontEnd/Application.py
- src/frontEnd/DockArea.py
- src/frontEnd/ProjectExplorer.py
- src/kicadtoNgspice/KicadtoNgspice.py
- src/kicadtoNgspice/Model.py
- src/kicadtoNgspice/Processing.py
- src/modelEditor/ModelEditor.py
- src/ngspiceSimulation/pythonPlotting.py
- src/projManagement/Kicad.py
- src/projManagement/Validation.py
- src/projManagement/Worker.py
- src/projManagement/newProject.py
- src/projManagement/openProject.py
**PR Details-**
- Used `autopep8`
- Manual fixes to remove pep8 errors and fix travis build
- Resolves #100
> Made pep8 compliant, Resolves #100

- src/frontEnd/ProjectExplorer.py
- src/ngspiceSimulation/NgspiceWidget.py
- src/ngspiceSimulation/pythonPlotting.py
- src/projManagement/Validation.py
- src/subcircuit/Subcircuit.py
- src/subcircuit/uploadSub.py
**Main Files to be considered**
- src/subcircuit/uploadSub.py added
- src/subcircuit/Subcircuit.py modified
- src/projmanagement/Validation.py 
- Added function validateSubcir() to check the validity of the .sub file.
> Upload subcircuit

- src/frontEnd/Application.py
- src/frontEnd/ProjectExplorer.py
- Added trigger for renameProject method
- Restored commented code for OMEdit
> rename project, OMEdit

- src/ngspicetoModelica/ModelicaUI.py
- src/ngspicetoModelica/NgspicetoModelica.py
Added a search bar for OpenModelica and the commands for running OMEdit
> OM Search Options

- src/ngspiceSimulation/NgspiceWidget.py
Added commands for GTK Analog Wave(GAW) Viewer. If  GAW is installed, then eSim will run GAW commands.
> Added commands for GTK Analog Wave Viewer

- src/maker/NgVeri.py
- Temp. fix to report the correct status of the Verilog to Ngspice conversion.
- Ideally, a message box should display the status.
> Fix incorrect status reporting on NgVeri UI terminal

- src/kicadtoNgspice/DeviceModel.py
- src/kicadtoNgspice/Model.py
Upload hex files for MCU circuits modules added. 
addHex and uploadHex modules defined.
By Sumanto and Jay
> Hex Upload added - Fellowship21

- src/frontEnd/ProjectExplorer.py
#209 is the issue where project explorer is not updating project files appropriately when required.
In this method, a new function **refreshInstant()** has been created that is triggered when QTreeWidget is expanded and then calls **refreshProject()** function. Also, a parameter **indexItem=None** is added in **refreshProject()** for better functioning.
> Resolved Project Files Refresh Problem

- src/kicadtoNgspice/DeviceModel.py
- src/kicadtoNgspice/SubcircuitTab.py
- Disabled file path editing by the user for ****Transistor, Diode, JFET, and MOSFET libraries**** in Device Modelling Tab of KicadtoNgspice window.
- Disabled file path editing by the user for ****Subcircuit path**** in Subcircuit Tab of KicadtoNgspice window.
> File path readonly for KicadtoNgspice Tabs

- Ubuntu/README.md
- Ubuntu/install-eSim-sky130.sh
- Ubuntu/install-eSim.sh
- Windows/README.md
- Windows/esim-setup-script-sky130.nsi
OS-specific installer scripts for installing SKY130 PDK
> SKY130 install scripts

- src/frontEnd/Application.py
- src/frontEnd/ProjectExplorer.py
- src/kicadtoNgspice/Analysis.py
- src/kicadtoNgspice/KicadtoNgspice.py
- src/kicadtoNgspice/Processing.py
- PR #210 doesn't allow project files to be viewed and modified in the text box
- Circuit element index not being continuous crashes eSim
- Refresh the project only when the user interacts with a directory in the project explorer
- Iterate circuit element through a relative index
> Fix explorer file open and circuit element crash

- src/kicadtoNgspice/KicadtoNgspice.py
- src/kicadtoNgspice/Model.py
- Added a new Microcontroller tab in the KicadtoNgspice window of Esim. Users can now directly interact with this window for microcontroller simulation
- Added add_hex() function in Microcontroller tab. Users can now directly upload the hex file into the respective NGHDL model folder just by entering the path of the hex file.
Related PR: https://github.com/FOSSEE/nghdl/pull/86
> Added Microcontroller tab in KicadtoNgspice and add_Hex function

- src/kicadtoNgspice/Convert.py
- src/kicadtoNgspice/KicadtoNgspice.py
- src/kicadtoNgspice/Microcontroller.py
- src/kicadtoNgspice/Model.py
- src/kicadtoNgspice/Processing.py
- src/kicadtoNgspice/TrackWidget.py
- Added a new **Microcontroller** tab in the KicadtoNgspice window of Esim. Users can now directly interact with this window for microcontroller simulation
- Added **add_hex()** function in Microcontroller tab. Users can now directly upload the hex file into the respective NGHDL model folder just by entering the path of the hex file.
- Added the functionality of simulation of **Multiple Instances of Microcontroller** in a circuit.
The updated GUI looks as below:
Related PRs: https://github.com/FOSSEE/eSim/pull/204 https://github.com/FOSSEE/nghdl/pull/86
> Added Multiple Instance Functionality And Updated GUI

- Ubuntu/install-eSim.sh
- Windows/README.md
- Windows/esim-setup-script.nsi
eSim installer support for KiCad V6.0.11.
Related PR: https://github.com/FOSSEE/eSim/pull/255
> Port KiCad v6 installers for eSim

- Ubuntu/install-eSim.sh
Improves installation reliability for Ubuntu 23.04.
The install-eSim.sh script needed improvements for better compatibility with Ubuntu 23.04, including:
> Ensuring proper installation of NgVeri dependencies.
> Addressing package installation issues due to outdated sources.list.
> Updated installDependency to correctly install NgVeri and other required modules.
> Automated virtual environment handling, including creation, activation, and cleanup.
> Added detection and update of sources.list to ensure smooth package installation.
These changes improve installation reliability and maintainability for Ubuntu 23.04.
> install-eSim.sh for Ubuntu 23.04

- Ubuntu/install-eSim-scripts/install-eSim-22.04.sh
- Ubuntu/install-eSim-scripts/install-eSim-23.04.sh
- Ubuntu/install-eSim-scripts/install-eSim-24.04.sh
- Ubuntu/install-eSim.sh
Fixes #277
The installer script lacked the capability to detect and handle different Ubuntu versions (22.04, 23.04, and 24.04), which could cause installation failures or improper behavior on these systems. This update adds version detection to improve compatibility and user experience.
- Enhanced the installer script to detect Ubuntu versions 22.04, 23.04, and 24.04.
- Added conditional handling to support installation steps specific to these versions.
- Tested on Ubuntu 22.04 , 23.04 , and 24.04 environments to ensure smooth operation.
> Installer script updated to detect and support Ubuntu 22.04, 23.04, and 24.04 during installation

- Ubuntu/install-eSim-scripts/install-eSim-22.04.sh
- Ubuntu/install-eSim-scripts/install-eSim-23.04.sh
- Ubuntu/install-eSim-scripts/install-eSim-24.04.sh
#246  Volare to automate SKY130 installation
> Installers (Using Volare to automate SKY130 installation)

- src/ngspiceSimulation/NgspiceWidget.py
1. there was a missing import statement that was missing from the file NgspiceWidget.py 
2. added ' from configparser import ConfigParser '
> fixed the missing import statement
